zip: digit.zip digit_stupid_broadcast.zip



digit.zip: digit
	7za a -tzip digit.zip digit

digit_stupid_broadcast.zip: digit_stupid_broadcast
	7za a -tzip digit_stupid_broadcast.zip digit_stupid_broadcast

clean:
	rm digit.zip digit_stupid_broadcast.zip